version: '3.8'

services:
  app:
    image: kube-node-manager:latest
    container_name: kube-node-manager-prod
    environment:
      - PORT=8080
      - GIN_MODE=release
      - DATABASE_DSN=./data/kube-node-manager.db
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE_TIME=${JWT_EXPIRE_TIME:-86400}
      - LDAP_ENABLED=${LDAP_ENABLED:-false}
      - LDAP_HOST=${LDAP_HOST}
      - LDAP_PORT=${LDAP_PORT:-389}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_USER_FILTER=${LDAP_USER_FILTER}
      - LDAP_ADMIN_DN=${LDAP_ADMIN_DN}
      - LDAP_ADMIN_PASS=${LDAP_ADMIN_PASS}
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./backend/configs:/app/configs:ro
      - ~/.kube:/home/appuser/.kube:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: kube-node-manager-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge

volumes:
  data:
    driver: local