apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kube-node-manager

resources:
  - configmap.yaml
  - k8s-statefulset.yaml
  - k8s-service.yaml
  - k8s-ingress.yaml

commonLabels:
  app: kube-node-manager
  version: v1.0.14

namespace: default

images:
  - name: kube-node-manager
    newName: reg.deeproute.ai/deeproute-public/zzh/kube-node-manager
    newTag: latest