# Go 构建阶段
FROM golang:1.23-alpine

WORKDIR /app

# 修改源
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk update

# 安装必要工具
RUN apk add --no-cache git ca-certificates tzdata gcc musl-dev sqlite-dev

# 安装 statik
RUN go install github.com/rakyll/statik@latest
